# SQL类型
SELECT = 'SELECT'
INSERT = 'INSERT'
UPDATE = 'UPDATE' 
DELETE = 'DELETE' 
TRUNCATE = 'TRUNCATE' 
DROP = 'DROP'
CREATE = 'CREATE'

# 数据类型
BIGINT_PRIMARY_KEY = 'BIGINT_PRIMARY_KEY' 
VARCHAR_PRIMARY_KEY = 'VARCHAR_PRIMARY_KEY' 
BIGINT = 'BIGINT' 
INT = 'INT'
TEXT = 'TEXT'
LONGTEXT = 'LONGTEXT'
INT_0 = 'INT_0'
VARCHAR = 'VARCHAR'
